=== is13mael/LMSGI-ISMAEL/Lenguaje de Marcas/Ejercicios XML/Ejemplo.dtd
<!ELEMENT raiz (table+)>
<!ELEMENT table (tr*,name?,color?,material?)>
<!ELEMENT tr (#PCDATA|td|tr)*>
<!ELEMENT td (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT material (#PCDATA)>

=== is13mael/LMSGI-ISMAEL/Lenguaje de Marcas/Ejercicios XML/Ejemplo.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE raiz  SYSTEM "Ejemplo.dtd">
<raiz>
    <table>
        <tr>
            <td>Platanos</td>
            <td>Manzanas</td>
        </tr>
        <tr>
            <tr>Fresas</tr>
            <tr>Sandias</tr>
        </tr>
    </table>

    <table>
        <name>Mesa aparador IKEA Kr√∂gen</name>
        <color>Negro</color>
        <material>Nogal</material>
    </table>
</raiz>
